apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: legacy-crm-backend
  annotations:
    github.com/project-slug: dcohen213/legacy-crm-backend
spec:
  type: other
  lifecycle: unknown
  owner: rhdh-team
